spring.application.name=oasis

server.port=5002
server.address=0.0.0.0
# PostgreSQL Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Schema Configuration
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}

spring.jpa.hibernate.ddl-auto=update
spring.output.ansi.enabled=always
spring.jpa.properties.hibernate.format_sql=true

frontend.url=${FRONTEND_URL}


#========================================
#   MAIL ENVIRONMENT
#========================================
spring.jpa.show-sql=${DB_SQL}
mail.host=${MAIL_HOST}
mail.port=${MAIL_PORT}
mail.id=${MAIL_ID}
mail.password=${MAIL_PASSWORD}
mail.auth=${MAIL_AUTH}
mail.ssl=${MAIL_SSL}
mail.starttls=${MAIL_TLS}
email.transport.protocol=${MAIL_PROTOCOL}

#========================================
#   IMAGEKIT CONFIGURATION
#========================================
imagekit.public-key=public_Pqrmx7iBgK1lqTCSQZ9N6kfEknI=
imagekit.private-key=private_1ZqkgHOU4QyOqqrgipLF0eZtNNw=
imagekit.url-endpoint=https://ik.imagekit.io/eur1zq65p

#========================================
#   CLOUDINARY CONFIGURATION
#========================================
cloudinary.cloud-name=dkxei4b5s
cloudinary.api-key=676427825871499
cloudinary.api-secret=N1IkkDZN72MT8imtldClpoNCUfQ

jwt.secret=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
