name: Build and Deploy to VM

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Define IMAGE_TAG from commit SHA
      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # -------------------------------
      # 3️⃣ Build Client Docker (inject VITE_BASE_URL)
      # -------------------------------
      - name: Build Client Docker
        run: |
          docker build \
            --build-arg VITE_BASE_URL=${{ secrets.BACKEND_URL }} \
            -t client-image ./client

      # -------------------------------
      # 4️⃣ Build Server Docker
      # -------------------------------
      - name: Build Server Docker
        run: docker build -t server-image ./server

      # -------------------------------
      # 5️⃣ Push Images to Docker Hub
      # -------------------------------
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Client Image
        run: |
          docker tag client-image ${{ secrets.DOCKER_USERNAME }}/oasis-client:latest
          docker tag client-image ${{ secrets.DOCKER_USERNAME }}/oasis-client:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/oasis-client:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/oasis-client:${TAG}

      - name: Tag and Push Server Image
        run: |
          docker tag server-image ${{ secrets.DOCKER_USERNAME }}/oasis-server:latest
          docker tag server-image ${{ secrets.DOCKER_USERNAME }}/oasis-server:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/oasis-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/oasis-server:${TAG}

      # -------------------------------
      # 6️⃣ Deploy to VM via SSH and Docker Compose
      # -------------------------------
      - name: Deploy to VM using Docker Compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "~/oasis-temp/"

      - name: Run Docker Compose on VM
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd ~/oasis-temp

            # Export secrets for docker-compose
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export DB_URL=${{ secrets.DB_URL }}
            export FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            export TAG=${TAG}

            # Pull & restart containers
            docker-compose pull
            docker-compose down
            docker-compose up -d

            # Remove docker-compose.yml after use
            rm -f docker-compose.yml
